apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: my-app
        image: 063388721629.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2:my-app
        ports:
        - containerPort: 8080
        env:
          - name: DBUSER
            value: "root"
          - name: DATABASE
            value: "employees"
          - name: DBPWD
            valueFrom:
            secretKeyRef:
              name: db-password
              key: MYSQL_ROOT_PASSWORD
          - name: APP_COLOR
            value: "blue"
          - name: DBHOST
            value: "10.244.0.2"
          - name: DBPORT
            value: "3306"
        imagePullSecrets:
        - name: ecr-secret